#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-flexmix
Version  : 2.3.20
Release  : 58
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/flexmix_2.3-20.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/flexmix_2.3-20.tar.gz
Summary  : Flexible Mixture Modeling
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-modeltools
BuildRequires : R-modeltools
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
models using the EM algorithm is implemented. The E-step and all
  data handling are provided, while the M-step can be supplied by the
  user to easily define new models. Existing drivers implement
  mixtures of standard linear models, generalized linear models and
  model-based clustering.

%prep
%setup -q -n flexmix
pushd ..
cp -a flexmix buildavx2
popd
pushd ..
cp -a flexmix buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740755700

%install
export SOURCE_DATE_EPOCH=1740755700
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/flexmix/CITATION
/usr/lib64/R/library/flexmix/DESCRIPTION
/usr/lib64/R/library/flexmix/INDEX
/usr/lib64/R/library/flexmix/Meta/Rd.rds
/usr/lib64/R/library/flexmix/Meta/data.rds
/usr/lib64/R/library/flexmix/Meta/features.rds
/usr/lib64/R/library/flexmix/Meta/hsearch.rds
/usr/lib64/R/library/flexmix/Meta/links.rds
/usr/lib64/R/library/flexmix/Meta/nsInfo.rds
/usr/lib64/R/library/flexmix/Meta/package.rds
/usr/lib64/R/library/flexmix/Meta/vignette.rds
/usr/lib64/R/library/flexmix/NAMESPACE
/usr/lib64/R/library/flexmix/NEWS.Rd
/usr/lib64/R/library/flexmix/R/flexmix
/usr/lib64/R/library/flexmix/R/flexmix.rdb
/usr/lib64/R/library/flexmix/R/flexmix.rdx
/usr/lib64/R/library/flexmix/data/BregFix.RData
/usr/lib64/R/library/flexmix/data/Mehta.RData
/usr/lib64/R/library/flexmix/data/NPreg.RData
/usr/lib64/R/library/flexmix/data/Nclus.RData
/usr/lib64/R/library/flexmix/data/NregFix.RData
/usr/lib64/R/library/flexmix/data/betablocker.RData
/usr/lib64/R/library/flexmix/data/bioChemists.RData
/usr/lib64/R/library/flexmix/data/candy.RData
/usr/lib64/R/library/flexmix/data/dmft.RData
/usr/lib64/R/library/flexmix/data/fabricfault.RData
/usr/lib64/R/library/flexmix/data/patent.RData
/usr/lib64/R/library/flexmix/data/salmonellaTA98.txt.gz
/usr/lib64/R/library/flexmix/data/seizure.RData
/usr/lib64/R/library/flexmix/data/tribolium.RData
/usr/lib64/R/library/flexmix/data/trypanosome.RData
/usr/lib64/R/library/flexmix/data/whiskey.RData
/usr/lib64/R/library/flexmix/doc/bootstrapping.R
/usr/lib64/R/library/flexmix/doc/bootstrapping.Rnw
/usr/lib64/R/library/flexmix/doc/bootstrapping.pdf
/usr/lib64/R/library/flexmix/doc/flexmix-intro.R
/usr/lib64/R/library/flexmix/doc/flexmix-intro.Rnw
/usr/lib64/R/library/flexmix/doc/flexmix-intro.pdf
/usr/lib64/R/library/flexmix/doc/index.html
/usr/lib64/R/library/flexmix/doc/mixture-regressions.R
/usr/lib64/R/library/flexmix/doc/mixture-regressions.Rnw
/usr/lib64/R/library/flexmix/doc/mixture-regressions.pdf
/usr/lib64/R/library/flexmix/doc/myConcomitant.R
/usr/lib64/R/library/flexmix/doc/mymclust.R
/usr/lib64/R/library/flexmix/doc/regression-examples.R
/usr/lib64/R/library/flexmix/doc/regression-examples.Rnw
/usr/lib64/R/library/flexmix/doc/regression-examples.pdf
/usr/lib64/R/library/flexmix/doc/ziglm.R
/usr/lib64/R/library/flexmix/help/AnIndex
/usr/lib64/R/library/flexmix/help/aliases.rds
/usr/lib64/R/library/flexmix/help/flexmix.rdb
/usr/lib64/R/library/flexmix/help/flexmix.rdx
/usr/lib64/R/library/flexmix/help/paths.rds
/usr/lib64/R/library/flexmix/html/00Index.html
/usr/lib64/R/library/flexmix/html/R.css
